// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	null "github.com/guregu/null/v5"
)

type Device struct {
	ID          int64
	Name        string
	Token       string
	LastSync    null.Time
	SleepsUntil null.Time
}

type Image struct {
	ID            int64
	DeviceID      int64
	Permanent     bool
	DataOriginal  string
	DataProcessed string
}
